
INSERT INTO RESEARCH.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_SEQ,STATUS) VALUES ('PD','Product Development',1,'A');
INSERT INTO RESEARCH.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_SEQ,STATUS) VALUES ('QA','Quality Analyst',2,'A');
INSERT INTO RESEARCH.DEPARTMENT (DEPT_CODE,DEPT_NAME,DEPT_SEQ,STATUS) VALUES ('IT','Infra Team',3,'A');
